### ISSUE TITLE
"Loading …" never gets replaced with content

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [caponetto/vscode-diff-viewer#83] opened 2023-06-27 19:48 UTC
I'm just getting this when attempting to open a git diff of my staged changes:

<img width="706" alt="Screenshot 2023-06-27 at 2 46 28 PM" src="https://github.com/caponetto/vscode-diff-viewer/assets/200/34673224-0518-43a7-a63e-212dc9e73e64">

I don't _think_ there's any related errors in the developer console. If it's related (and I find it often is, with extensions), I'm on VScode-Remote over SSH.

**Comment by scfrazer** [comment] 2023-08-10 13:23
I'm seeing the same thing using remove-through-ssh.  It works fine locally

**Comment by scfrazer** [comment] 2023-08-10 13:38
More info:  I don't see any problems in the logs, but if I start the developer tools and try to open a diff file, it shows:
![image](https://github.com/caponetto/vscode-diff-viewer/assets/178275/5c5bcc7e-ced5-4595-b910-b1b7394402db)
This does not happen when run locally.  No idea why it's trying to find Django -- or why it fails -- since I don't use that or have any extensions that explicitly do.  I mean to say I don't have any Django extensions installed, but it could be some other extension.

**Comment by scfrazer** [comment] 2023-08-10 13:53
Sorry for spamming comments, but:  [This issue](https://github.com/rtfpessoa/diff2html/issues/501) looks like it might be the same thing, and was fixed just three days ago.  Maybe just need to pick up a newer version of diff2html?

**Comment by caponetto** [comment] 2023-08-12 14:04
Hi @scfrazer, no problems, thanks for the pointers. :)
I have updated the version of `diff2html` to the one that includes that fix (PR https://github.com/caponetto/vscode-diff-viewer/pull/86).
Could you please give it a try and let me know?
The vsix is available to be downloaded [here](https://github.com/caponetto/vscode-diff-viewer/actions/runs/5841726148?pr=86), in the Artifacts section.

**Comment by scfrazer** [comment] 2023-08-14 13:25
> Hi @scfrazer, no problems, thanks for the pointers. :) I have updated the version of `diff2html` to the one that includes that fix (PR #86). Could you please give it a try and let me know? The vsix is available to be downloaded [here](https://github.com/caponetto/vscode-diff-viewer/actions/runs/5841726148?pr=86), in the Artifacts section.

Shoot, that didn't fix it.

I'm pretty sure it's not a remote vs. local problem.  I have seen it work remotely even before trying the new vsix.  What I work on locally (mostly Typescript) vs. what I work on remotely (mostly SystemVerilog/Python) is very different.  I'm guessing it's some other extension that is causing the issue, either by simply existing or maybe by the order they are loaded or activated.  I don't have a reliable way to reproduce the passing/failing behaviors yet to test any sort of a fix.  I'll try to figure something out, maybe disabling all extensions then bisecting until I find a problem.

**Comment by jacekkopecky** [comment] 2023-08-14 14:27
@scfrazer does that diff file load OK in some circumstances and not in others?

If it never loads properly, you could try subsetting the file to identify which part of it triggers the issue.

**Comment by scfrazer** [comment] 2023-08-14 16:55
> @scfrazer does that diff file load OK in some circumstances and not in others?
> 
> If it never loads properly, you could try subsetting the file to identify which part of it triggers the issue.

You're right, it may be the diff file itself.  I tried disabling everything except vscode-diff-viewer and it still won't load.  Let me try playing with the diff file and see if I can figure out the issue

**Comment by scfrazer** [comment] 2023-08-14 17:10
Okay I found it.  I am using Jinja template files and that is messing up diff2html.  When I look in that repo, I see that it sets the file mode to Django for Jinja templates.  I don't know if the person who originally started this thread is using Jinja or maybe another format that diff2html doesn't support, but as far as I'm concerned this is not your issue.  Thanks for the help!

**Comment by scfrazer** [comment] 2023-08-14 17:24
Again sorry for spamming comments :)  A quick look at the diff2html lib shows that there is a "full" and "slim" version.  The slim version leaves out syntax highlighting for some file types, Django being one of them.  You are [using the slim version](https://github.com/caponetto/vscode-diff-viewer/blob/29a6ea7cd067543976f6191d6482a1910c0c5544/src/webview/message/handler.ts#L1), would you be willing to switch to the "full" version of diff2html?  Granted diff2html should gracefully handle non-existent syntax highlighting file types, and I'll probably comment just that in diff2html if I can figure out where it is happening.

**Comment by caponetto** [comment] 2023-08-26 17:59
Hi @scfrazer. Not a problem switching to the full version. Would you mind making this change locally to see if it resolves for you? PR is welcome :)

**Comment by scfrazer** [comment] 2023-08-26 19:16
I opened an issue in diff2html and the maintainer just replied.  He gave some suggestions I can try first, and if that isn't working out try the non-slim version.  I'll open a PR once I figure something out.

**Comment by scfrazer** [comment] 2023-08-28 14:49
@caponetto , after some back-and-forth with the diff2html maintainer, there is a new version that handles this situation properly.  I just made a PR to pick up the new diff2html, which I tested locally and it works: #88

**Comment by caponetto** [comment] 2023-08-29 09:54
Thanks for the PR @scfrazer! It will be included in the next release (`1.4.2`).

**Closed** 2023-09-09 10:45 UTC
